### ISSUE TITLE
Stops working in HA 2025.12.0

### ISSUE THREAD

**Issue by pantherale0** [basnijholt/adaptive-lighting#1289]
# Home Assistant Adaptive Lighting Issue Template

## Bug Reports

If you need help with using or configuring Adaptive Lighting, please [open a Q&A discussion thread here](https://github.com/basnijholt/adaptive-lighting/discussions/new?category=q-a) instead.

### Before submitting a bug report, please follow these troubleshooting steps:

Please confirm that you have completed the following steps:

- [X] I have updated to the [latest Adaptive Lighting version](https://github.com/basnijholt/adaptive-lighting/releases) available in [HACS](https://hacs.xyz/).
- [X] I have reviewed the [Troubleshooting Section](https://github.com/basnijholt/adaptive-lighting#sos-troubleshooting) in the [README](https://github.com/basnijholt/adaptive-lighting#readme).
- [X] (If using Zigbee2MQTT) I have read the [Zigbee2MQTT troubleshooting guide](https://github.com/basnijholt/adaptive-lighting#zigbee2mqtt) in the [README](https://github.com/basnijholt/adaptive-lighting#readme).
- [X] I have checked the [V2 Roadmap](https://github.com/basnijholt/adaptive-lighting/discussions/291) and [open issues](https://github.com/basnijholt/adaptive-lighting/issues) to ensure my issue isn't a duplicate.

### Required information for bug reports:

After upgrading to 2025.12.0b0, this integration stops working:

```
Logger: homeassistant.config_entries
Source: config_entries.py:730
First occurred: 18:37:37 (9 occurrences)
Last logged: 18:37:37

Error importing platform config_flow from integration adaptive_lighting to set up adaptive_lighting configuration entry: cannot import name 'area_entities' from 'homeassistant.helpers.template' (/usr/src/homeassistant/homeassistant/helpers/template/__init__.py)
```

This is likely due to the implementation of https://github.com/home-assistant/core/pull/156629

**Comment by MaJerle** [comment]
https://github.com/basnijholt/adaptive-lighting/issues/1290
