### ISSUE TITLE
Mixed results after upgrading to Home Assistant 2021.5

### ISSUE THREAD

**Issue by DigitalFeonix** [basnijholt/adaptive-lighting#112]
After upgrading my HA install to 2021.5, the lights that I had configured to work with Adaptive Lighting only half worked. I had set up four entities - two Ecosmart zigbee bulbs via ZHA and two Shelly Duo bulbs via the built-in integration. They were all working before the update.

After the update, the zigbee bulbs continue to work with Adaptive Lighting and the Shelly bulbs stopped. I had the four entities selected as the lights in the integration, but after noticing the Shelly bulbs not changing color or brightness I checked the Adaptive Lighting options dialog and the two Shelly bulbs were no longer listed, nor available for selection in the dropdown box.

I tried replacing the entities with a light group that all four bulbs belong to instead and that still allowed the zigbee bulbs to work, but not the Shelly Duo's. I can still manually control the Shelly's brightness and temp via their individual entities or the light group itself.

I believe that Adaptive Lighting needs to be updated to handle the new [color modes](https://www.home-assistant.io/blog/2021/05/05/release-20215/#color-modes) introduced in 2021.5.

**Comment by fredamn76** [comment]
I have the same issue when turning on adaptive lighting 
`[140526038688048] 'tuple' object has no attribute 'sunrise'`

**Comment by DigitalFeonix** [comment]
As a follow up here are some screenshots of the entities in dev tools

This lights works with adaptive lighting
![image](https://user-images.githubusercontent.com/197201/117349414-34270d00-ae60-11eb-9d0a-c2b9160989fc.png)

This light does not
![image](https://user-images.githubusercontent.com/197201/117349503-4c972780-ae60-11eb-94c5-819ec65dd5e8.png)

It appears that when they [added color modes to the Shelly lights](https://github.com/home-assistant/core/pull/49867/commits/2cd018865c8e29e2b4c4c02fb910ff5cdd518c90) it removed the supported features that adaptive lighting checks against.

**Comment by pjmbarlick** [comment]
Same issue here with Philips Hue bulbs integrated via ZHA :(

**Comment by austwhite** [comment]
Definitely having the same issue.  I think it may have something to do with Home Assistant changing the colour picker to now support RGBW and RGBWW.
The colour behaviour seems a bit random

**Comment by chpego** [comment]
Did you see here #110 ?

**Comment by basnijholt** [comment]
Did you guys update to the latest version?

**Comment by austwhite** [comment]
I installed mine via HACS 3 days ago, so I assume it is latest version.  HACS is not reporting an update

**Comment by austwhite** [comment]
> Did you see here #110 ?

Had not seen that as I did not search closed issues.  I only installed Adaptive Lighting for first time 3 days ago

**Comment by basnijholt** [comment]
@DigitalFeonix, I am pretty sure that you are having this issue because the light reports `supported_features: 0` which is incorrect.

This means that your light reports that it is not possible to do brightness adjustments or color adjustments. Hence, Adaptive-lighting won't try to do those.

**Comment by austwhite** [comment]
Mine is not related to supported features.  I might try a clean install on a test Raspberry Pi 3B+ and test a clean install in case something weird happened during the update to 2021.5

**Comment by filmgarage** [comment]
Does this apply to both the standard "Shelly" integration and the "ShellyForHass" integration? Or just one of the two?

**Comment by lvarado** [comment]
Similar issue here, also with Shelly bulbs (Vintage instead of Duo; brightness only). I'm using the ShellyForHass integration from HACS, and enabling adaptive lighting always sets the brightness to 1%.

![shelly](https://user-images.githubusercontent.com/32886847/117546249-176d0f80-afef-11eb-9003-fe9f52cf27de.png)

![adaptive](https://user-images.githubusercontent.com/32886847/117546386-bdb91500-afef-11eb-94a8-1e8046ad2a5d.png)

My other lights (RGB TP-Link Kasa) seem to work totally fine and brightness is at 100% as expected. I installed adaptive lighting this morning after upgrading HA and learning the circadian lighting integration no longer works, so I have the latest version.

**Comment by beyondtenor** [comment]
I have the same issue with my LIFX bulbs as well. I haven’t checked the Hue bulbs as those are in rooms I don’t use this for, but I’ll give it a shot tomorrow to be sure.

**Comment by broyuken** [comment]
I’m on the latest version of HA, AL and tasmota and I’m having this same issue with my novastella tasmota bulb. It worked fine pre-upgrade.

**Comment by MrLemur** [comment]
Unfortunately seeing the same issue with Tasmota. Debug log shows no errors. Works as expected with zigbee2mqtt devices.

**Comment by basnijholt** [comment]
Could the people that are having issues confirm that it's like @DigitalFeonix mentioned [above](https://github.com/basnijholt/adaptive-lighting/issues/112#issuecomment-834642357)?

Basically, that the lights that are not working have `supported_color_modes` and not `supported_features` (or it being set to 0).

If this is the reason, I will try to fix this ASAP.

**Comment by broyuken** [comment]
My light is supported_features: 36

**Comment by MrLemur** [comment]
Here's one of my Tasmota lamps (running 9.2, with the new HA native integration)
![image](https://user-images.githubusercontent.com/17055328/117680365-ffd98680-b1a8-11eb-9612-594fdac36e30.png)

**Comment by basandsuus** [comment]
Not working for me as well...

min_mireds: 153
max_mireds: 454
supported_color_modes:
  - color_temp
color_mode: color_temp
brightness: 255
color_temp: 178

supported_features: 40
type: light-color-temp
room: dining room

**Comment by FsFalcon** [comment]
It's no longer working for me on a Shelly RGBW2:

> supported_color_modes:
>   - rgbw
> friendly_name: Kitchen Cabinets
> icon: 'mdi:led-strip-variant'
> supported_features: 0

One thing I noticed just today is that when I go to configure it via the integration menu, the corresponding entity is no longer available in the 'lights' list.  It still shows the entity I set originally (light.kitchen_cabinets in this case), but any attempt to change it will drop that value, and it's no longer availab in the drop-down selection.

**Comment by basnijholt** [comment]
I have attempted to add support for the `supported_color_modes` option.

Unfortunately, I cannot try these myself because all my lights still work.

If someone could report whether it works, that would be great!

**Comment by broyuken** [comment]
I don’t see a new release in hacs. Do we need to manually install it?

**Comment by basnijholt** [comment]
Click on "Update information":
![image](https://user-images.githubusercontent.com/6897215/117693712-96647280-b1be-11eb-90f2-1681d3bbd2d7.png)

Maybe then it will show that there's an update.

**Comment by MrLemur** [comment]
Color temp changes now seem to work, just not brightness changes.

**Comment by DigitalFeonix** [comment]
> I have attempted to add support for the `supported_color_modes` option.
> 
> Unfortunately, I cannot try these myself because all my lights still work.
> 
> If someone could report whether it works, that would be great!

I updated and am seeing the same thing as @MrLemur. My Shelly bulbs will now shift color temp, but not brightness (turning on sleep mode the easiest way to test).

My understanding would be that all the color modes support brightness except `COLOR_MODE_ONOFF` and `COLOR_MODE_UNKNOWN`.

**Comment by FsFalcon** [comment]
> I had to add Adaptive Lighting again as an integration in HACS, it didn't show up for me anymore.

@disrupted  - I had the same issue; I think it was why I missed the initial update that @basnijholt posted.  I'm not sure of the cause though....

@basnijholt  - The update appears to have fixed the issue I was having with a Shelly RGBW2; brightness & color temp now update/change as expected, and the entity once again appears in the configuration options as expected.

Thank you for your quick response to this, it is very much appreciated!

**Comment by basnijholt** [comment]
I have assumed that what @DigitalFeonix wrote above is correct:
> My understanding would be that all the color modes support brightness except COLOR_MODE_ONOFF and COLOR_MODE_UNKNOWN.

and implemented that assumption. 

@broyuken and @MrLemur, can you try if this works for you now?

**Comment by MrLemur** [comment]
> I have assumed that what @DigitalFeonix wrote above is correct:
> 
> > My understanding would be that all the colour modes support brightness except COLOR_MODE_ONOFF and COLOR_MODE_UNKNOWN.
> 
> and implemented that assumption.
> 
> @broyuken and @MrLemur, can you try if this works for you now?

Bravo! Working as expected now with Tasmota bulbs. Tested with just changing brightness and temp in white mode, and then turning off and on. Also tested changing to a colour, and when turned back it is set to the correct white temperature.

**Comment by MrLemur** [comment]
> I have assumed that what @DigitalFeonix wrote above is correct:
> 
> > My understanding would be that all the color modes support brightness except COLOR_MODE_ONOFF and COLOR_MODE_UNKNOWN.
> 
> and implemented that assumption.
> 
> @broyuken and @MrLemur, can you try if this works for you now?

Bravo! Working as expected now with Tasmota bulbs. Tested with just changing brightness and temp in white mode, and then turning off and on. Also tested changing to a colour, and when turned back it is set to the correct white temperature.

**Comment by broyuken** [comment]
Will have to test when my son wakes up from his nap. His is the only tasmota bulb I have.

**Comment by broyuken** [comment]
Seems to be good now

**Comment by basnijholt** [comment]
Great! I’ll close this issue then 😃

**Comment by mcheijink** [comment]
@basnijholt Thank you for the quick fix! My Hue bulbs are also functioning again!

**Comment by TheAlphaLaw** [comment]
> @basnijholt Thank you for the quick fix! My Hue bulbs are also functioning again!

My hue bulbs are not working. They only transition from min to max temp, but nothing in-between.

**Comment by beyondtenor** [comment]
It appears my LIFX and cheap zigbee lights are working perfectly. Hue tends to work 75% of the time. But all in all I’m a very satisfied customer. :) anything I can do to help let me know!!

**Comment by austwhite** [comment]
I use mostly Hue globes and all of mine are working fine now.
Had the nunistall and reinstall the integration but after that all was good.

**Comment by TheAlphaLaw** [comment]
@basnijholt  @austwhite 

With Hue lights via Deconz, the lights adjust to 2200 kelvin at sunrise and 5000 kelvin at sunset. Those are my minimum bad maximum settings. No changes in-between (although the correct temperatures are reflected in the adaptive light component).

**Comment by austwhite** [comment]
> @basnijholt @austwhite
> 
> With Hue lights via Deconz, the lights adjust to 2200 kelvin at sunrise and 5000 kelvin at sunset. Those are my minimum and maximum settings. No changes in-between (although the correct temperatures are reflected in the adaptive light component).

That's odd, I have used DeConz (the up.e assistant plugin version) for all my Hue lamps for a long time and on latest versions and HA 2021.5.5 the colour temp is no issue.
Are you using with the RGB option on or off?
i have a combination of Ambience white and full colour lamps and all work fine.   
During the evening they dim and colour temp drops evenly from 5500(my max) down to 2000 (my min).
It seems to be hit and miss.  Works for me in Australia.  Maybe location nos affecting it too?

**Comment by TheAlphaLaw** [comment]
> > @basnijholt @austwhite
> > With Hue lights via Deconz, the lights adjust to 2200 kelvin at sunrise and 5000 kelvin at sunset. Those are my minimum and maximum settings. No changes in-between (although the correct temperatures are reflected in the adaptive light component).
> 
> That's odd, I have used DeConz (the home assistant plugin version) for all my Hue lamps for a long time and on latest versions and HA 2021.5.5 the colour temp is no issue.
> Are you using with the RGB option on or off?
> i have a combination of Ambience white and full colour lamps and all work fine.
> During the evening they dim and colour temp drops evenly from 5500(my max) down to 2000 (my min).
> It seems to be hit and miss. Works for me in Australia. Maybe location is affecting it too?
> As a note, all my Hue globes are on the latest Hue firmware also. Mine are all the older ones with no Bluetooth. That may make a difference.

Using Deconz on windows. All Hue ambiance.

**Comment by austwhite** [comment]
Maybe there is a difference between DeConz in Windows and the Docker version included as a HA add-on.   
I definitely do not have the same issue using DeConz add-on.

**Comment by th3w1zard1** [comment]
Would like to point out this is fixed, see the diff since 2021.5.0:
`git diff 2021.5.0 dev homeassistant/components/light/__init__.py`
